apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raiz
  template:
    metadata:
      labels:
        app: raiz
    spec:
      containers:
        - name: go
          image: rafaelcmd/go-hpa:latest
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
